// constantes para os tokens 
enum {EQUIVALENTTO=1, INDIVIDUALS, SUBCLASSOF, DISJOINTCLASSES, ONLY,SOME,ALL,VALUE,MIN,MAX,EXACTLY,THAT,NOT,AND,OR, PROPRIEDADES, HAS, IS, NUM, RELOP,RESERVADO, CLASS, TDADOS}; 
